(() => {
 const $=id=>document.getElementById(id),db=window.supabase.createClient(window.CBL_SUPABASE_URL,window.CBL_SUPABASE_KEY);let current=null;
 const msg=t=>{$('msg').textContent=t};const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 async function refresh(){const {data,error}=await db.from('products').select('*').order('created_at',{ascending:false});if(error){$('list').textContent='Erro ao carregar catálogo: '+error.message;return;}$('list').innerHTML=data.length?data.map(p=>`<div class="item"><img src="${esc(p.image_url||'assets/logo-cbl.png')}" alt=""><div><b>${esc(p.name)}</b><p class="status">${esc(p.status)} · ${p.price==null?'Preço não definido':'R$ '+Number(p.price).toFixed(2).replace('.',',')}</p></div><button data-edit="${p.id}">EDITAR</button><button data-delete="${p.id}">EXCLUIR</button></div>`).join(''):'Nenhuma peça cadastrada.';$('list').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(data.find(p=>p.id===b.dataset.edit)));$('list').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete));}
 function show(){ $('login').classList.add('hidden');$('panel').classList.remove('hidden');refresh();}
 async function session(){const {data}=await db.auth.getSession();if(data.session){current=data.session.user;show();}}
 $('loginForm').onsubmit=async e=>{e.preventDefault();msg('Entrando…');const {data,error}=await db.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error){msg('Não foi possível entrar: '+error.message);return;}current=data.user;show();};
 $('logout').onclick=async()=>{await db.auth.signOut();location.reload()};
 function reset(){ $('productForm').reset();$('pid').value='';$('formTitle').textContent='Adicionar peça';msg('');}
 $('reset').onclick=reset;
 function edit(p){$('pid').value=p.id;$('name').value=p.name;$('price').value=p.price??'';$('size').value=p.size??'';$('category').value=p.category??'';$('condition').value=p.condition??'Usado — ótimo estado';$('status').value=p.status;$('measurements').value=p.measurements??'';$('description').value=p.description??'';$('formTitle').textContent='Editar peça';window.scrollTo({top:0,behavior:'smooth'});}
 $('productForm').onsubmit=async e=>{e.preventDefault();msg('Salvando…');let image_url=null;const file=$('photo').files[0];if(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const path=`${crypto.randomUUID()}.${ext}`;const {error:upErr}=await db.storage.from('product-images').upload(path,file,{upsert:false,contentType:file.type||'image/jpeg'});if(upErr){msg('Erro ao enviar foto: '+upErr.message);return;}image_url=db.storage.from('product-images').getPublicUrl(path).data.publicUrl;}
 const row={name:$('name').value.trim(),description:$('description').value.trim(),price:$('price').value===''?null:Number($('price').value),size:$('size').value.trim(),category:$('category').value.trim(),condition:$('condition').value,measurements:$('measurements').value.trim(),status:$('status').value,updated_at:new Date().toISOString()};if(image_url)row.image_url=image_url;
 const id=$('pid').value;const result=id?await db.from('products').update(row).eq('id',id):await db.from('products').insert(row);if(result.error){msg('Erro ao salvar: '+result.error.message);return;}msg('Peça salva!');reset();await refresh();};
 async function remove(id){if(!confirm('Excluir esta peça permanentemente?'))return;const {error}=await db.from('products').delete().eq('id',id);if(error){alert('Erro ao excluir: '+error.message);return;}refresh();}
 session();
})();
