(() => {
 const $=s=>document.querySelector(s); const root=window.CBL_SUPABASE_URL; const key=window.CBL_SUPABASE_KEY;
 if(!window.supabase||!root||!key){$('#products').innerHTML='<div class="empty">Não foi possível iniciar a loja. Confira a conexão do Supabase.</div>';return;}
 const db=window.supabase.createClient(root,key); const money=v=>v==null?'Consulte o preço':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 async function load(){const host=$('#products');host.innerHTML='<div class="loading">Buscando o garimpo…</div>';const {data,error}=await db.from('products').select('*').eq('status','published').order('created_at',{ascending:false});if(error){host.innerHTML='<div class="empty">Não foi possível carregar as peças. Verifique as permissões do catálogo no Supabase.</div>';console.error(error);return;}$('#count').textContent=`${data.length} ${data.length===1?'PEÇA DISPONÍVEL':'PEÇAS DISPONÍVEIS'}`;if(!data.length){host.innerHTML='<div class="empty">Ainda não há peças publicadas. Volte em breve!</div>';return;}host.innerHTML=data.map(p=>`<article class="product" data-id="${p.id}"><img loading="lazy" src="${esc(p.image_url||'assets/logo-cbl.png')}" alt="${esc(p.name)}"><div class="pinfo"><h3>${esc(p.name)}</h3><p>${esc([p.category,p.size,p.condition].filter(Boolean).join(' · '))}</p><span class="price">${money(p.price)}</span></div></article>`).join('');host.querySelectorAll('.product').forEach(el=>el.addEventListener('click',()=>detail(data.find(p=>p.id===el.dataset.id))));}
 function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
 function detail(p){$('#mimg').src=p.image_url||'assets/logo-cbl.png';$('#mimg').alt=p.name;$('#mtitle').textContent=p.name;$('#mdesc').textContent=p.description||'Consulte os detalhes pelo WhatsApp.';$('#mmeta').textContent=[p.size&&`Tamanho: ${p.size}`,p.condition,p.measurements].filter(Boolean).join(' · ');$('#mprice').textContent=money(p.price);$('#buy').href=`https://wa.me/5511912646444?text=${encodeURIComponent('Olá! Tenho interesse na peça: '+p.name)}`;$('#modal').classList.remove('hidden');}
 $('#close').addEventListener('click',()=>$('#modal').classList.add('hidden'));$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')});load();
})();
